#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KIRO_DIR="$HOME/.kiro"

echo ""
echo "👋 Kiro Weekly Report Setup"
echo "============================"
echo ""
echo "This will install /save-session and /weekly-report skills."
echo "Make sure you've completed google/GOOGLE_SETUP.md steps 1-5 first."
echo ""

# --- Step 1: Personal info ---
echo "Step 1/4: Personal info"
echo "-----------------------"
read -p "  Worker ID (e.g. CW-0011): " WORKER_ID
read -p "  Full name (e.g. John Doe): " FULL_NAME
echo ""

# --- Step 2: Projects ---
echo "Step 2/4: Projects"
echo "------------------"
PROJECTS=""
while true; do
  read -p "  Jira project key (e.g. FOTL): " PROJ_KEY
  read -p "  Project human name (e.g. AI QA Tool): " PROJ_NAME
  PROJECTS="${PROJECTS}  ${PROJ_KEY}: \"${PROJ_NAME}\"\n"
  read -p "  Add another project? (y/n): " ADD_MORE
  [[ "$ADD_MORE" != "y" ]] && break
  echo ""
done
echo ""

# --- Step 3: Google config ---
echo "Step 3/4: Google integration"
echo "----------------------------"
echo "  How do you want to save reports?"
echo "    1) Monthly subfolders (e.g. 06-June/)"
echo "    2) Single folder (everything in one place)"
echo "    3) No Google Sheets (terminal + local file only)"
echo ""
read -p "  Choose (1/2/3): " SHEETS_CHOICE

case $SHEETS_CHOICE in
  1) SHEETS_MODE="monthly_folders" ;;
  2) SHEETS_MODE="single_folder" ;;
  3) SHEETS_MODE="none" ;;
  *) SHEETS_MODE="monthly_folders" ;;
esac

if [[ "$SHEETS_MODE" != "none" ]]; then
  echo ""
  echo "  (See google/GOOGLE_SETUP.md if you haven't done this yet)"
  echo ""
  read -p "  Apps Script Web App URL: " APPS_SCRIPT_URL
  read -p "  Template spreadsheet ID: " TEMPLATE_ID
  read -p "  Root Drive folder ID (holds per-year subfolders): " ROOT_FOLDER_ID
  read -p "  Current year folder ID (subfolder for $(date +%Y) inside root): " YEAR_FOLDER_ID
else
  APPS_SCRIPT_URL=""
  TEMPLATE_ID=""
  ROOT_FOLDER_ID=""
  YEAR_FOLDER_ID=""
fi
echo ""

# --- Step 4: Install ---
echo "Step 4/4: Installing..."
echo "-----------------------"

# Create directories
mkdir -p "$KIRO_DIR/skills/save-session"
mkdir -p "$KIRO_DIR/skills/weekly-report"
mkdir -p "$KIRO_DIR/work-planning/work-log"
mkdir -p "$KIRO_DIR/work-planning/sessions"
mkdir -p "$KIRO_DIR/work-planning/reports"

# Copy skills
cp "$SCRIPT_DIR/skills/save-session/SKILL.md" "$KIRO_DIR/skills/save-session/SKILL.md"
cp "$SCRIPT_DIR/skills/weekly-report/SKILL.md" "$KIRO_DIR/skills/weekly-report/SKILL.md"
echo "  ✓ Skills installed"

# Copy holidays
cp "$SCRIPT_DIR/shared/holidays-2026.yaml" "$KIRO_DIR/holidays-2026.yaml"
echo "  ✓ Holidays file installed"

# Generate work-config.yaml
cat > "$KIRO_DIR/work-config.yaml" << EOF
# Kiro Work Config — generated by setup.sh
worker_id: "${WORKER_ID}"
full_name: "${FULL_NAME}"
activity: "Soft. Dev"
default_hours: 8
projects:
$(echo -e "$PROJECTS")
# Global dirs — independent of which project directory the CLI was launched from
work_log_dir: "~/.kiro/work-planning/work-log"
sessions_dir: "~/.kiro/work-planning/sessions"
reports_dir: "~/.kiro/work-planning/reports"

# How reports are saved to Google Sheets:
#   monthly_folders — subfolders per month inside root_folder_id
#   single_folder  — all reports in root_folder_id directly
#   none           — no Google Sheets, terminal + local file only
sheets_mode: "${SHEETS_MODE}"
EOF
echo "  ✓ work-config.yaml created"

# Generate folders.yaml (only if Google Sheets enabled)
if [[ "$SHEETS_MODE" != "none" ]]; then
  cat > "$KIRO_DIR/skills/weekly-report/folders.yaml" << EOF
apps_script_url: "${APPS_SCRIPT_URL}"
template_id: "${TEMPLATE_ID}"
root_folder_id: "${ROOT_FOLDER_ID}"
year: $(date +%Y)
year_folder_id: "${YEAR_FOLDER_ID}"
months: {}
EOF
  echo "  ✓ folders.yaml created"
else
  echo "  ⏭ folders.yaml skipped (sheets_mode: none)"
fi

echo ""
echo "🎉 Done!"
echo ""
echo "Files created:"
echo "  $KIRO_DIR/skills/save-session/SKILL.md"
echo "  $KIRO_DIR/skills/weekly-report/SKILL.md"
echo "  $KIRO_DIR/skills/weekly-report/folders.yaml"
echo "  $KIRO_DIR/work-config.yaml"
echo "  $KIRO_DIR/holidays-2026.yaml"
echo ""
echo "Try it: open Kiro CLI and say 'weekly report current week'"
echo ""
