#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KIRO_DIR="$HOME/.kiro"

echo ""
echo "👋 Kiro Weekly Report Setup"
echo "============================"
echo ""
echo "This will install /save-session-v2 and /weekly-report-v2 skills."
echo "Make sure you've completed google/GOOGLE_SETUP.md steps 1-5 first."
echo ""

# --- Step 1: Personal info ---
echo "Step 1/4: Personal info"
echo "-----------------------"
read -p "  Worker ID (e.g. CW-0011): " WORKER_ID
read -p "  Full name (e.g. John Doe): " FULL_NAME
echo ""

# --- Step 2: Projects ---
echo "Step 2/4: Projects"
echo "------------------"
PROJECTS=""
while true; do
  read -p "  Jira project key (e.g. FOTL): " PROJ_KEY
  read -p "  Project human name (e.g. AI QA Tool): " PROJ_NAME
  PROJECTS="${PROJECTS}  ${PROJ_KEY}: \"${PROJ_NAME}\"\n"
  read -p "  Add another project? (y/n): " ADD_MORE
  [[ "$ADD_MORE" != "y" ]] && break
  echo ""
done
echo ""

# --- Step 3: Google config ---
echo "Step 3/4: Google integration"
echo "----------------------------"
echo "  (See google/GOOGLE_SETUP.md if you haven't done this yet)"
echo ""
read -p "  Apps Script Web App URL: " APPS_SCRIPT_URL
read -p "  Root Drive folder ID: " ROOT_FOLDER_ID
echo ""

# --- Step 4: Install ---
echo "Step 4/4: Installing..."
echo "-----------------------"

# Create directories
mkdir -p "$KIRO_DIR/skills/save-session-v2"
mkdir -p "$KIRO_DIR/skills/weekly-report-v2"
mkdir -p "$KIRO_DIR/work-log"

# Copy skills
cp "$SCRIPT_DIR/skills/save-session-v2/SKILL.md" "$KIRO_DIR/skills/save-session-v2/SKILL.md"
cp "$SCRIPT_DIR/skills/weekly-report-v2/SKILL.md" "$KIRO_DIR/skills/weekly-report-v2/SKILL.md"
echo "  ✓ Skills installed"

# Copy holidays
cp "$SCRIPT_DIR/shared/holidays-2026.yaml" "$KIRO_DIR/holidays-2026.yaml"
echo "  ✓ Holidays file installed"

# Generate work-config.yaml
cat > "$KIRO_DIR/work-config.yaml" << EOF
# Kiro Work Config — generated by setup.sh
worker_id: "${WORKER_ID}"
full_name: "${FULL_NAME}"
activity: "Soft. Dev"
default_hours: 8
projects:
$(echo -e "$PROJECTS")work_log_dir: "~/.kiro/work-log"
sessions_dir: ".planning/sessions"
EOF
echo "  ✓ work-config.yaml created"

# Generate folders.yaml
cat > "$KIRO_DIR/skills/weekly-report-v2/folders.yaml" << EOF
apps_script_url: "${APPS_SCRIPT_URL}"
root_folder_id: "${ROOT_FOLDER_ID}"
year: 2026
months: {}
EOF
echo "  ✓ folders.yaml created"

echo ""
echo "🎉 Done!"
echo ""
echo "Files created:"
echo "  $KIRO_DIR/skills/save-session-v2/SKILL.md"
echo "  $KIRO_DIR/skills/weekly-report-v2/SKILL.md"
echo "  $KIRO_DIR/skills/weekly-report-v2/folders.yaml"
echo "  $KIRO_DIR/work-config.yaml"
echo "  $KIRO_DIR/holidays-2026.yaml"
echo ""
echo "Try it: open Kiro CLI and say 'weekly report v2 current week'"
echo ""
